from bs4 import BeautifulSoup
import re


def strip_internal_tags(html_content):
    """Remove all internal tags within paragraphs, preserving only text content"""
    soup = BeautifulSoup(html_content, "html.parser")

    for p in soup.find_all("p"):
        # Get all text content, stripping tags
        clean_text = p.get_text(" ", strip=True)
        # Replace the paragraph with clean text
        p.string = clean_text

    return soup


def split_paragraphs(soup):
    """Split paragraphs at sentence boundaries"""
    paragraphs = soup.find_all("p")

    for p in paragraphs:
        text = p.get_text()
        # Skip if too short
        if len(text) < 15:
            continue

        # Split sentences (multilingual support)
        sentences = re.split(r"(?<=[.!?…。！？])\s+", text)

        # Only split if we have multiple sentences
        if len(sentences) > 1:
            # Clear original paragraph and keep first sentence
            p.string = sentences[0].strip()

            # Add remaining sentences as new paragraphs after current one
            current = p
            for sentence in sentences[1:]:
                if len(sentence.strip()) >= 15:  # Minimum length
                    new_p = soup.new_tag("p")
                    new_p.string = sentence.strip()
                    current.insert_after(new_p)
                    current = new_p

    return soup


def process_epub_content(html_content):
    """Full processing pipeline"""
    # First strip all internal tags
    soup = strip_internal_tags(html_content)
    # Then split paragraphs
    return split_paragraphs(soup)


# Example usage
sample_html = """
<p><span class="font5">Sebbene qui Lacan descriva una scena assai comune - un gruppo di persone che a teatro si gode la rappresentazione di una tragedia greca - la lettura che egli ne offre rende evidente l’accadere di qualcosa di strano: è come se una qualche figura dell’altro - in&nbsp;questo caso il Coro - potesse subentrare al nostro posto e fare&nbsp;esperienza per noi degli atteggiamenti e dei sentimenti più intimi&nbsp;e spontanei che ci appartengono, compresi il ridere e il piangere.&nbsp;In alcune società, il medesimo ruolo è rivestito dalle cosiddette&nbsp;«prefiche» (donne ingaggiate per piangere ai funerali), che interpretano lo spettacolo del lutto per i congiunti del defunto permettendo loro di dedicare il proprio tempo a sforzi più redditizi (come&nbsp;spartirsi l’eredità). Qualcosa di simile accade con i mulini di pre</span><span style="font-size: 1em; line-height: 1.1em; text-indent: 1.5em;">ghiera del Tibet: basta che io attacchi alla ruota un pezzetto di carta sul quale sia vergata la preghiera, giri meccanicamente la&nbsp;ruota (o, in maniera ancor più pratica, lasci che siano il vento o&nbsp;l’acqua a farla girare), ed ecco che il mulino prega per me. Gli stalinisti avrebbero detto che «oggettivamente» sto pregando, poco&nbsp;importa se la mia mente è impegnata nelle più oscene fantasie sessuali. Per sfatare l’illusione che cose simili accadano solo nelle società primitive, basta pensare alla risata preconfezionata degli&nbsp;spettacoli televisivi: la reazione di ilarità a una scena comica è già&nbsp;inclusa nella sua colonna sonora. Quand’anche non ridessi, ma,&nbsp;provato da una dura giornata di lavoro, me ne stessi semplicemente a fissare lo schermo, mi sentirei comunque sollevato dopo&nbsp;la trasmissione, come se la colonna sonora avesse riso per me.</span></p>

  <p><span class="font5">Per afferrare correttamente questo bizzarro processo, bisognerebbe integrare la nozione, oggi alla moda, di interattività con il suo inusitato doppio, ossia l'</span><span class="font5" style="font-style:italic;">interpassività.<sup>2</sup></span> <span class="font5">È un luogo comune enfatizzare come, con i nuovi media elettronici, non si dia più fruizione passiva di un testo o di un’opera d’arte: non fisso più semplicemente lo schermo, ma sempre più interagisco con esso e con&nbsp;esso entro in una relazione dialogica (dallo scegliere i programmi,&nbsp;al partecipare ai dibattiti in una comunità virtuale, al determinare&nbsp;direttamente il finale di una trama nei cosiddetti «racconti interattivi»). Chi decanta il potenziale democratico dei nuovi media si&nbsp;concentra in genere proprio su queste caratteristiche, su come,&nbsp;cioè, il cyberspazio apra a una grande maggioranza di persone la&nbsp;possibilità di smarcarsi dal ruolo di osservatori passivi costretti ad&nbsp;assistere a uno spettacolo inscenato da altri, permettendo loro di&nbsp;partecipare attivamente non solo allo spettacolo, ma anche e sempre più alla costituzione delle sue regole.</span></p>

  <p><span class="font5">L’altra faccia di questa interattività è l’interpassività. L’inverso dell’interazione con l’oggetto (invece di limitarsi a seguire passivamente lo spettacolo) è la situazione nella quale l’oggetto mi&nbsp;prende, mi espropria della mia passività, cosicché è l’oggetto stesso a godere dello spettacolo al mio posto, sollevandomi dal dovere&nbsp;di goderne a mia volta. Pressoché qualsiasi aficionado del videore</span><span class="font5" style="font-size: 1em; line-height: 1.1em; text-indent: 1.5em;">gistratore che registri compulsivamente film (io sono fra loro), sa bene che l’effetto immediato del possedere un videoregistratore è&nbsp;che si guardano</span> <span class="font5" style="font-size: 1em; line-height: 1.1em; text-indent: 1.5em; font-style: italic;">meno</span> <span class="font5" style="font-size: 1em; line-height: 1.1em; text-indent: 1.5em;">film di quanto non si facesse ai bei vecchi&nbsp;tempi del semplice apparecchio televisivo. Non si ha mai il tempo&nbsp;per guardare la televisione, così, anziché perdere una preziosa serata, non si fa che registrare il film, archiviandolo per una futura&nbsp;visione (per la quale, ovviamente, non vi è quasi mai il tempo).&nbsp;Benché io non guardi realmente quei film, la sola consapevolezza&nbsp;che le pellicole che amo siano archiviate nella mia videoteca mi dà&nbsp;una profonda soddisfazione, permettendomi talvolta di indulgere&nbsp;alla dolce arte del</span> <span class="font5" style="font-size: 1em; line-height: 1.1em; text-indent: 1.5em; font-style: italic;">far niente</span><span class="font5" style="font-size: 1em; line-height: 1.1em; text-indent: 1.5em;"><sup>3</sup></span><span class="font5" style="font-size: 1em; line-height: 1.1em; text-indent: 1.5em; font-style: italic;">,</span> <span class="font5" style="font-size: 1em; line-height: 1.1em; text-indent: 1.5em;">come se il videoregistratore le stesse,&nbsp;in qualche modo,</span> <span class="font5" style="font-size: 1em; line-height: 1.1em; text-indent: 1.5em; font-style: italic;">guardando per me, al mìo posto.</span> <span class="font5" style="font-size: 1em; line-height: 1.1em; text-indent: 1.5em;">Il videoregistratore gioca qui il ruolo del grande Altro, il medium della registrazione simbolica. Sembra che, al giorno d’oggi, persino la pornografia funzioni sempre più in modo interpassivo. I film a luci&nbsp;rosse, infatti, non hanno più lo scopo precipuo di eccitare chi ne&nbsp;fruisce in vista della sua asociale attività masturbatoria: il solo fissare lo schermo dove «l’azione ha luogo» è sufficiente, mi è sufficiente osservare come altri godono al mio posto.</span></p>

  <p><span class="font5">Ma ecco un altro esempio di interpassività: tutti conosciamo la scena imbarazzante in cui una persona racconta una barzelletta di&nbsp;cattivo gusto e, quando nessuno ride, è lui stesso a scoppiare in&nbsp;una fragorosa risata continuando a ripetere «questa è buona» o&nbsp;qualche altro commento del genere; in altre parole, è lui stesso a&nbsp;interpretare la reazione che si attendeva dal pubblico. Qui la situazione è simile a quella della risata preregistrata, ma al tempo&nbsp;stesso se ne differenzia: in questo caso, l’agente [</span><span class="font5" style="font-style:italic;">agent]</span> <span class="font5">che ride al&nbsp;nostro posto (attraverso il quale noi, pubblico annoiato e imbarazzato, nonostante tutto ridiamo) non coincide con l’anonimo&nbsp;grande Altro dell’invisibile pubblico artificiale, ma con la stessa&nbsp;persona che racconta la barzelletta. La sua risata compulsiva suona&nbsp;come quegli «Oops!» che ci sentiamo in dovere di proferire quando scivoliamo in qualche sciocchezza o facciamo qualcosa di stupido. Il mistero di quest’ultimo caso è che vi è anche la possibilità&nbsp;che qualcuno che abbia solamente assistito al nostro strafalcione&nbsp;dica «Oops!»</span> <span class="font5" style="font-style:italic;">per noi</span> <span class="font5">e che ciò funzioni. L’ufficio dell’«Oops!» è di&nbsp;avviare la registrazione simbolica del passo falso, poiché il grande&nbsp;Altro virtuale deve esserne informato. Pensiamo alla tipica situazione critica in cui tutte le persone di un gruppo ristretto conoscono un qualche particolare scabroso (e sanno anche che tutti gli&nbsp;altri ne sono a conoscenza), ma quando uno di loro inavvertitamente si lascia sfuggire quel particolare, tutti ne sono imbarazzati.&nbsp;Perché? Se nessuno viene a sapere nulla di nuovo, per quale motivo&nbsp;si sentono tutti imbarazzati? Perché non possono più</span> <span class="font5" style="font-style:italic;">fingere</span> <span class="font5">di non&nbsp;saperne nulla (comportarsi come se non ne sapessero nulla) o, in&nbsp;altre parole, perché ora</span> <span class="font5" style="font-style:italic;">il grande Altro lo sa.</span> <span class="font5">In questo consiste la&nbsp;lezione dei</span> <span class="font5" style="font-style:italic;">Vestiti nuovi dell’imperatore</span> <span class="font5">di Hans Christian Andersen:&nbsp;non bisognerebbe mai sottovalutare il potere delle apparenze. Talvolta, quando inavvertitamente disturbiamo l’apparenza, anche la&nbsp;cosa stessa che si nasconde dietro l’apparenza cade a pezzi.</span></p>

  <p><span class="font5">L’interpassività è l’opposto della nozione hegeliana di</span> <span class="font5" style="font-style:italic;">List der Vemunft</span> <span class="font5">(astuzia della Ragione), nella quale</span> <span class="font5" style="font-style:italic;">io sono attivo attraverso l’Altro</span><span class="font5">: io posso rimanere passivo, sedere comodamente sullo&nbsp;sfondo, mentre l’Altro agisce per me. Non occorre che io percuota&nbsp;il metallo con un martello, quando la macchina lo può fare per me;&nbsp;anziché essere io a far girare la ruota del mulino, l’acqua lo può fare&nbsp;al mio posto: raggiungo il mio scopo ponendo, fra me e l’oggetto&nbsp;sul quale lavoro, un altro oggetto naturale. Lo stesso può accadere sul piano interpersonale: anziché attaccare direttamente il mio&nbsp;nemico, fomento una lite fra lui e un’altra persona, in modo da&nbsp;poter comodamente osservare i due mentre si distruggono a vicenda.&nbsp;(È così che, secondo Hegel, l’Idea assoluta regna sovrana in tutta&nbsp;la storia. Essa rimane estranea al conflitto, lasciando che siano le&nbsp;passioni umane, nelle loro mutue contese, a fare il suo lavoro. In&nbsp;questa prospettiva, la necessità storica del passaggio dalla repubblica all’impero nell’antica Roma si realizzò utilizzando come suo strumento le passioni e le ambizioni di Giulio Cesare.)</span></p>

  <p><span class="font5">Al contrario, nel caso dell’interpassività,</span> <span class="font5" style="font-style:italic;">io sono passivo attraverso l’Altro.</span> <span class="font5">Concedo all’Altro l’aspetto passivo (il godere) della mia esperienza, rimanendo frattanto attivamente impegnato (posso&nbsp;continuare a lavorare la sera, mentre il videoregistratore gode passivamente del film al mio posto; posso stipulare accordi finanziari&nbsp;circa la fortuna del deceduto, mentre le prefiche si addolorano per&nbsp;me). Siamo così condotti alla nozione di</span> <span class="font5" style="font-style:italic;">falsa attività:</span> <span class="font5">le persone&nbsp;</span><span style="font-size: 1em; line-height: 1.1em; text-indent: 1.5em;">non agiscono solo in modo da cambiare qualcosa, ma possono anche agire per impedire che qualcosa accada, perché nulla cambi. In ciò risiede la strategia tipica del nevrotico ossessivo, che è freneticamente&nbsp;attivo per evitare che la cosa reale avvenga. Per esempio, in una situazione di gruppo nella quale una tensione minacci di esplodere,&nbsp;l’ossessivo parla tutto il tempo in modo da evitare l’inopportuno momento di silenzio che costringerebbe i partecipanti ad affrontare&nbsp;apertamente la tensione sottintesa. Nel trattamento psicoanalitico, i&nbsp;nevrotici ossessivi parlano in continuazione, sommergendo l’analista&nbsp;di aneddoti, sogni, intuizioni: la loro incessante attività è motivata&nbsp;dalla paura sotterranea che, se smettessero di parlare per un momento, l’analista porrebbe loro la questione davvero decisiva; in altre&nbsp;parole, parlano in modo da mantenere l’analista immobile.</span></p>

  <p><span class="font5">Persino in molta dell’odierna politica progressista, il pericolo non è costituito dalla passività, quanto dalla pseudoattività, dal bisogno, cioè, di essere attivi e di partecipare. La gente interviene&nbsp;tutto il tempo tentando di «fare qualcosa», gli accademici partecipano a dibattiti insensati. La cosa davvero difficile, in questo&nbsp;senso, è fare un passo indietro e ritirarsi. Per coinvolgerci in un&nbsp;dialogo, per assicurarsi che la nostra infausta passività sia spezzata, chi è al potere spesso preferisce che vi sia, se non altro, una&nbsp;partecipazione critica al silenzio. Contro questa impostazione interpassiva - nella quale siamo costantemente attivi per sincerarci&nbsp;che nulla effettivamente cambi - il primo passo davvero critico da&nbsp;fare è</span> <span class="font5" style="font-style:italic;">ritirarsi nella passività</span> <span class="font5">e rifiutarsi di partecipare. Questo&nbsp;primo passo prepara il terreno a una vera attività, a un’azione che&nbsp;effettivamente cambi le coordinate della scena.</span></p>

  <p><span class="font5">Qualcosa di simile a questa falsa attività lo si incontra nella nozione protestante di Predestinazione. Il paradosso della Predestinazione è che la stessa teologia, secondo cui il nostro destino è predeterminato e la nostra salvezza non dipende dalle nostre azioni, servì a legittimare il capitalismo, ossia il sistema sociale che scatenò&nbsp;la più frenetica attività produttiva della storia dell’umanità. Il&nbsp;mero fatto che le cose siano decise preliminarmente - che il nostro&nbsp;atteggiamento nei confronti del Fato sia quello di una vittima passiva - basta a impegnarci in un’incessante attività frenetica. Agiamo costantemente, insomma, per mantenere la fissità del grande&nbsp;Altro (in questo caso: Dio).</span></p>

  <p><span class="font5">Un tale spostamento dei nostri sentimenti e atteggiamenti più intimi su una qualche figura dell’Altro costituisce il nocciolo della&nbsp;nozione lacaniana del grande Altro, il quale può agire non solo sui&nbsp;nostri sentimenti, ma anche su credenze e conoscenza; in altre parole, l’Altro può anche credere e conoscere per me. Per designare&nbsp;questo spostamento della conoscenza del soggetto su un altro,&nbsp;Lacan coniò la nozione di</span> <span class="font5" style="font-style:italic;">soggetto supposto sapere.</span> <span class="font5">Nella serie televisiva</span> <span class="font5" style="font-style:italic;">II tenente Colombo,</span> <span class="font5">il crimine - ossia l’azione dell’omicidio -viene mostrato preliminarmente nel dettaglio, sicché l’enigma da&nbsp;risolvere non coincide con il «chi è stato?», ma con il modo attraverso il quale l’investigatore stabilirà il collegamento fra la superficie ingannevole (il «contenuto manifesto» della scena del crimine, per usare i termini della teoria freudiana dei sogni) e la verità&nbsp;sul crimine (il suo «pensiero latente»). L’enigma coincide, insomma, con il modo in cui l’investigatore proverà al colpevole la sua&nbsp;colpevolezza. Il successo del</span> <span class="font5" style="font-style:italic;">Tenente Colombo</span> <span class="font5">attesta il fatto che&nbsp;il vero motivo di interesse nel lavoro del detective è il processo&nbsp;stesso di decifrazione, non il suo risultato.</span></p>

  <p><span class="font5">Persino più cruciale di quest’ultima osservazione è però il fatto che non solo noi, gli spettatori, sappiamo in anticipo (dal momento che lo vediamo direttamente) chi sia l’autore del crimine, ma&nbsp;che, inspiegabilmente, il tenente Colombo stesso lo sappia subito:&nbsp;quando si reca sulla scena del crimine e incontra il colpevole, egli&nbsp;è assolutamente certo, semplicemente sa che quello è il colpevole.&nbsp;I suoi sforzi successivi non riguardano l’enigma del «Chi è stato?»,&nbsp;ma convergono sul come provare al colpevole la sua colpevolezza.&nbsp;Questa strana inversione dell’ordine normale ha connotazioni teologiche: in un’autentica credenza religiosa, anzitutto io credo in&nbsp;Dio e poi, sulla base della mia credenza, divento sensibile alle&nbsp;prove che sostengono la verità della mia fede. Analogamente, Colombo</span> <span class="font5" style="font-style:italic;">prima</span> <span class="font5">sa - con una certezza misteriosa e non di meno assolutamente infallibile - chi sia l’autore del crimine, e</span> <span class="font5" style="font-style:italic;">poi</span> <span class="font5">sulla base&nbsp;di questa inspiegabile conoscenza, passa a raccogliere le prove.</span></p>

  <p><span class="font5">Nella terapia, lo psicoanalista quale soggetto supposto sapere funziona in modo solo leggermente diverso da quello appena descritto: una volta intrapreso il trattamento, il paziente ha la stessa&nbsp;assoluta certezza che l’analista</span> <span class="font5" style="font-style:italic;">conosca</span> <span class="font5">il suo segreto (il che significa solo che il paziente</span> <span class="font5" style="font-style:italic;">è</span> <span class="font5">colpevole a priori di nascondere un se</span><span class="font5" style="font-size: 1em; line-height: 1.1em; text-indent: 1.5em;">greto, che vi</span> <span class="font5" style="font-size: 1em; line-height: 1.1em; text-indent: 1.5em; font-style: italic;">è</span> <span class="font5" style="font-size: 1em; line-height: 1.1em; text-indent: 1.5em;">un significato segreto da estrapolare dalle sue azioni). Il terapeuta non è un empirista che indaghi sul paziente formulando diverse ipotesi e cercando prove; al contrario, egli incorpora&nbsp;l’assoluta certezza (che Lacan paragona alla certezza cartesiana del&nbsp;</span><span class="font5" style="font-size: 1em; line-height: 1.1em; text-indent: 1.5em; font-style: italic;">cogito ergo sum)</span> <span class="font5" style="font-size: 1em; line-height: 1.1em; text-indent: 1.5em;">del desiderio inconscio del paziente. Per Lacan,&nbsp;questa strana trasposizione sulla figura dell’analista di quanto già&nbsp;conosco nel mio inconscio è alla base del fenomeno del transfert&nbsp;che ha luogo nel trattamento: posso giungere al significato inconscio dei miei sintomi solo se presuppongo che l’analista conosca già&nbsp;il loro significato. La differenza fra Freud e Lacan è che mentre&nbsp;Freud si concentrò sulle dinamiche fisiche del transfert inteso&nbsp;quale relazione intersoggettiva (il paziente trasferisce sulla figura&nbsp;dell’analista i sentimenti che riguardano suo padre, in modo che,&nbsp;quando sembra parlare dell’analista, «in realtà» sta parlando di&nbsp;suo padre), Lacan estrapolò dalla ricchezza empirica dei fenomeni&nbsp;legati al transfert la struttura formale del significato presupposto.</span></p>

  <p><span class="font5">La regola più generale esemplificata dal transfert è che spesso l’invenzione di un qualche nuovo contenuto può verificarsi soltanto nella forma illusoria del ritorno alla passata verità originaria.&nbsp;Per tornare al Protestantesimo: Lutero portò a termine la più grande rivoluzione nella storia della Cristianità pensando di non far&nbsp;altro che dissotterrare la verità offuscata da secoli di degenerazione cattolica. Lo stesso vale per la rivalsa nazionale: quando gruppi etnici si costituiscono come Stati-nazione, di solito formulano&nbsp;questa costituzione nei termini di un ritorno ad antiche nonché dimenticate radici etniche. Ciò di cui non sono consapevoli è che il&nbsp;loro «ritorno a» costituisce l’oggetto stesso del ritornare: proprio&nbsp;nell’atto di ritornare alla tradizione, essi la stanno inventando. Del&nbsp;resto, come ogni storico ben sa, i</span> <span class="font5" style="font-style:italic;">kilt</span> <span class="font5">scozzesi (nella forma in cui&nbsp;li conosciamo oggi) furono inventati nel corso del xix secolo.</span></p>

"""

soup = process_epub_content(sample_html)
print(soup.prettify())
